# Generated by Django 2.2.6 on 2019-10-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_domain', models.TextField()),
                ('depth', models.IntegerField()),
            ],
        ),
    ]
