# Generated by Django 2.2.6 on 2019-10-24 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input_data',
            name='depth',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
